### ISSUE TITLE
Wide tables

### ISSUE THREAD

**Issue by turnermm** [kvormweg/monochrome#3]
Wide tables extend  beyond the template's borders, most likely they are not being kept in a div with the correct overflow settings.  This  happens when there is a sidebar installed.  See:  https://mturner.org/devel/playground/test?do=

**Comment by kvormweg** [comment]
This should be corrected in the last commit. I have only tested it without a sidebar

**Comment by turnermm** [comment]
I seem to have the latest version:     2017-05-18
The issue is with the sidebar, as you will see if you click on the above cited link.  Thanks.

**Comment by kvormweg** [comment]
Please try the changed `design.css` and check if that solves your problem. If it does I will draft a new release.

**Comment by turnermm** [comment]
Where will I find it.  I've checked your distributions but none of the design.css files are recent.

**Comment by kvormweg** [comment]
Sorry, I meant `content.css` and you can find it on GitHub: `https://github.com/kvormweg/monochrome/blob/master/css/content.css`

**Comment by turnermm** [comment]
Thanks.  That works.
